import {createHash} from 'node:crypto';import type pg from 'pg';import {z} from 'zod';import {stableStringify} from '../evaluator/snapshot.js';import {deterministicAuditEventId,writeAuditEvent} from '../audit-ledger/write-audit-event.js';import {insertIdempotent} from '../../db/insert-idempotent.js';
const schema=z.object({clientId:z.uuid(),auditRunId:z.uuid()}).strict();
export class DiscoveryTriggerError extends Error{constructor(readonly code:'AUDIT_RUN_NOT_FOUND'|'TRIGGER_CONFLICT'){super(code.toLowerCase().replace(/_/g,' '));this.name='DiscoveryTriggerError';}}
interface Source{id:string;source_kind:'VARIANCE_FINDING'|'GATE_FAILURE';criterion_id:string;rule_version_id:string;evaluated_expr:unknown;detail:unknown}
export async function detectUnassessableTriggers(client:pg.PoolClient,untrusted:z.input<typeof schema>):Promise<{triggerIds:string[];createdCount:number}>{const input=schema.parse(untrusted);if(!(await client.query(`SELECT 1 FROM audit_run WHERE client_id=$1 AND id=$2`,[input.clientId,input.auditRunId])).rowCount)throw new DiscoveryTriggerError('AUDIT_RUN_NOT_FOUND');
 const rows=(await client.query<Source>(`SELECT vf.id,'VARIANCE_FINDING' source_kind,vf.criterion_id,vf.rule_version_id,vf.evaluated_expr,jsonb_build_object('classification',vf.classification,'status',vf.status) detail FROM variance_finding vf WHERE vf.client_id=$1 AND vf.audit_run_id=$2 AND vf.classification='unassessable'
 UNION ALL SELECT gf.id,'GATE_FAILURE',gf.criterion_id,gf.rule_version_id,gf.evaluated_expr,jsonb_build_object('defect',gf.defect,'citation',gf.citation) FROM gate_failure gf WHERE gf.client_id=$1 AND gf.audit_run_id=$2 AND gf.defect LIKE '% (unassessable)' ORDER BY source_kind,id`,[input.clientId,input.auditRunId])).rows;
 const ids:string[]=[];let createdCount=0;for(const row of rows){const hash=createHash('sha256').update(stableStringify(row.evaluated_expr)).digest('hex');const vf=row.source_kind==='VARIANCE_FINDING'?row.id:null;const gf=row.source_kind==='GATE_FAILURE'?row.id:null;const result=await insertIdempotent(client,{insertSql:`INSERT INTO discovery_trigger(client_id,trigger_type,audit_run_id,source_kind,variance_finding_id,gate_failure_id,criterion_id,rule_version_id,evaluated_expr_hash,detail) VALUES($1,'UNASSESSABLE_RESULT',$2,$3,$4,$5,$6,$7,$8,$9::jsonb) ON CONFLICT DO NOTHING`,insertParams:[input.clientId,input.auditRunId,row.source_kind,vf,gf,row.criterion_id,row.rule_version_id,hash,JSON.stringify(row.detail)],fallbackSql:`SELECT id FROM discovery_trigger WHERE client_id=$10 AND variance_finding_id IS NOT DISTINCT FROM $11::uuid AND gate_failure_id IS NOT DISTINCT FROM $12::uuid AND criterion_id=$13 AND rule_version_id=$14 AND evaluated_expr_hash=$15 AND detail IS NOT DISTINCT FROM $16::jsonb`,fallbackParams:[input.clientId,vf,gf,row.criterion_id,row.rule_version_id,hash,JSON.stringify(row.detail)]});if(result?.created)createdCount++;if(!result)throw new DiscoveryTriggerError('TRIGGER_CONFLICT');ids.push(result.id);}
 await writeAuditEvent(client,{id:deterministicAuditEventId(input.clientId,input.auditRunId,'unassessable-discovery'),clientId:input.clientId,entity:'discovery_trigger',entityId:input.auditRunId,event:'unassessable_detected',actorKind:'system',detail:{triggerIds:ids,triggerCount:ids.length}});return{triggerIds:ids,createdCount};}
